### ISSUE TITLE
Getting error while installing

### ISSUE THREAD

**Issue by munir131** [apache/pulsar-client-node#134]
I am getting below error while, I am trying to install this package on Alpine

```
bash-5.0# npm install pulsar-client
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> pulsar-client@1.2.0 install /app/node_modules/pulsar-client
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.2.0 and node@12.15.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
make: Entering directory '/app/node_modules/pulsar-client/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/Pulsar/src/addon.o
In file included from ../src/addon.cc:20:
../src/Message.h:24:10: fatal error: pulsar/c/message.h: No such file or directory
   24 | #include <pulsar/c/message.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Pulsar.target.mk:118: Release/obj.target/Pulsar/src/addon.o] Error 1
make: Leaving directory '/app/node_modules/pulsar-client/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.112+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/app/node_modules/pulsar-client/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/app/node_modules/pulsar-client/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /app/node_modules/pulsar-client
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/app/node_modules/pulsar-client/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.19.112+
node-pre-gyp ERR! command "/usr/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/pulsar-client
node-pre-gyp ERR! node -v v12.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/app/node_modules/pulsar-client/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

**Comment by equanz** [comment]
It seems that your app can't resolve pulsar C++ library. pulsar Node.js client requires pulsar C++ library (see [here](https://github.com/apache/pulsar-client-node#requirements)).
If you don't install pulsar C++ library now, please install it before installing pulsar Node.js client.

Currently official pulsar C++ prebuilt packages are served through DEV, RPM, and Homebrew. Therefore, if you want to install pulsar C++ library, please build pulsar C++ library or use another base image such as Ubuntu, CentOS.

**Comment by sijie** [comment]
@munir131 Can you check this comment https://github.com/apache/pulsar-client-node/issues/134#issuecomment-737630822 ?

**Comment by munir131** [comment]
@sijie Sure. I will try that.

**Comment by tschmidt64-SC** [comment]
I'm getting this same issue on MacOS (Big Sur 11.1). 

```bash
➜   ✗ brew reinstall libpulsar
==> Downloading https://homebrew.bintray.com/bottles/libpulsar-2.7.0_1.big_sur.bottle.tar.gz
Already downloaded: /Users/tschmidt/Library/Caches/Homebrew/downloads/10a657368d76e82fa87e89539a5f15bb16cbd032df49baf47b9712d3aa4fd8a0--libpulsar-2.7.0_1.big_sur.bottle.tar.gz
==> Reinstalling libpulsar
==> Pouring libpulsar-2.7.0_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libpulsar/2.7.0_1: 54 files, 19.9MB
➜   ✗ yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/3] ⠐ core-js
[2/3] ⠐ pulsar-client
error /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.18.1 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release/libpulsar.node" (not found)
node-pre-gyp http GET https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.1.0 and node@12.18.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v72-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.1 | darwin | x64
gyp info spawn /usr/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tschmidt/.node-gyp/12.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tschmidt/.node-gyp/12.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tschmidt/.node-gyp/12.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/tschmidt/.nvm/versions/node/v12.18.1/bin/node" "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/tschmidt/.nvm/versions/node/v12.18.1/bin/node /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 20.2.0
node-pre-gyp ERR! command "/Users/tschmidt/.nvm/versions/node/v12.18.1/bin/node" "/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client
node-pre-gyp ERR! node -v v12.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/tschmidt/.nvm/versions/node/v12.18.1/bin/node /Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tschmidt/skygrid/all-repos/skygrid-auth/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar
```

**Comment by hrsakai** [comment]
@tschmidt64-SC 
I couldn't be reproduced on MacOS(Mojave 10.14.6).

Could you try to upgrade pulsar-client-node to v1.2.0?
If not resolved, this issue seems to be related to node-gyp.
Please see node-gyp documents, issues or etc.
https://github.com/nodejs/node-gyp
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

**Comment by tschmidt64-SC** [comment]
I'm on 1.2.1 currently. I'll look into node-gyp and see if I can get it resolved that direction. Will report back after.

**Comment by tschmidt64-SC** [comment]
Does this section of the error log ring any bells?: 
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/tschmidt/skygrid/all-repos/skygrid-atc/node_modules/pulsar-client/build/Release/libpulsar.node" (not found)
node-pre-gyp http GET https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.2.0 and node@12.18.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz```

**Comment by hrsakai** [comment]
> Does this section of the error log ring any bells?:

No, please ignore that log.
We haven't uploaded libpulsar.node to the remote server.

**Comment by bulolo** [comment]
```
error /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.18.3 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node" (not found)
node-pre-gyp http GET https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.2.0 and node@12.18.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/.node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/hongjunyao/.node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/hongjunyao/.node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
```

**Comment by bulolo** [comment]
I switch Python 3 to 2 it on now

**Comment by munir131** [comment]
> @munir131 Can you check this comment [#134 (comment)](https://github.com/apache/pulsar-client-node/issues/134#issuecomment-737630822) ?

No it is not working. In that command node-gyp is looking for `--module=/app/node_modules/pulsar-client/build/Release/libpulsar.node` which is not there.

**Comment by munir131** [comment]
I am closing this issue. I find out manual way to install deb files on arch linux. Also found that dev cpp is missing for 2.7.1 https://archive.apache.org/dist/pulsar/pulsar-2.7.1/DEB/

**Comment by tschmidt64-SC** [comment]
I'm still having this issue to this day. Tried building in a docker container, same issue there.

**Comment by jskorlol** [comment]
I'm also trying to install it inside a docker container, but it doesn't work.
Any solution ?

**Comment by k2la** [comment]
@jskorlol
Installation instructions for rpm or debian have been added at https://github.com/apache/pulsar-client-node/pull/213. 
Please see https://github.com/apache/pulsar-client-node#install-on-linux and try again.
