### ISSUE TITLE
Is it possible to install pulsar-client-node library in windows 10 or Not?

### ISSUE THREAD

**Issue by AhmedAymanBfcai** [apache/pulsar-client-node#271]
I have windows 10. I was trying to install the pulsar-client-node library two weeks ago but am still stuck!

I see that: https://github.com/apache/pulsar-client-node/issues/122#issuecomment-694653352

When I try to build the C++ client on Windows, tons of tons of errors come!

Should I be quick?

**Comment by shibd** [comment]
@AhmedAymanBfcai  Hi, We are releasing v1.8.0, which is easy to install on Windows.

You can try running this: `npm install pulsar-client@1.8.0-rc.2`

**Comment by AhmedAymanBfcai** [comment]
@shibd Thank you very very much, Man:)

It works well, and seems Easy!

Here we go:)

**Comment by AhmedAymanBfcai** [comment]
Hi @shibd! It works well yesterday but I had to delete my own node_moduels and Install it again. When I am installing the specific version you give me. I have this error:

{
npm ERR! code 1
npm ERR! path D:\Devlopment\tagger\admin-service\node_modules\pulsar-client
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   nothing.c
npm ERR!   win_delay_load_hook.cc
npm ERR!   nothing.vcxproj -> D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\build\Release\\nothing.lib
npm ERR!   addon.cc
npm ERR! D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\src\Message.h(24,10): fatal  error C1083: Cannot open include file: 'pulsar/c/message.h': No such file or directory [D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\build\Pulsar.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\MATRIX\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\lib\binding\Pulsar.node --module_name=Pulsar --module_path=D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\lib\binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.12.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\lib\binding\Pulsar.node" (not found)
npm ERR! node-pre-gyp http GET https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-node/pulsar-client-node-1.8.0-candidate-2/napi-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-node/pulsar-client-node-1.8.0-candidate-2/napi-win32-unknown-x64.tar.gz   
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for pulsar-client@1.8.0-rc.2 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-node/pulsar-client-node-1.8.0-candidate-2/napi-win32-unknown-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.1 found at "C:\Users\MATRIX\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp info find VS using VS2022 (17.4.33205.214) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\MATRIX\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\MATRIX\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Devlopment\\tagger\\admin-service\\node_modules\\pulsar-client\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\MATRIX\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\MATRIX\\AppData\\Local\\node-gyp\\Cache\\18.12.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\MATRIX\\AppData\\Local\\node-gyp\\Cache\\18.12.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\MATRIX\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\MATRIX\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.12.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\Devlopment\\tagger\\admin-service\\node_modules\\pulsar-client',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\Devlopment\\tagger\\admin-service\\node_modules\\pulsar-client\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\MATRIX\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MATRIX\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Devldule=D:\\Devlopment\\tagger\\admin-service\\node_modules\\pulsar-client\\lib\\binding\\Pulsar.node" "--module_name=Pulsar" "--module_path=D:\\Devlopment\\tagger\\admin-service\\node_modules\\pulsar-clienng" "--napi_vt\\lib\\binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd D:\Devlopment\tagger\admin-service\node_modules\pulsar-client
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\MATRIX\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --modulbuild --module=D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\lib\binding\Pulsar.node --module_name=Pulsar --module_path=D:\Devlopment\tagger\admin-service\node_modules\pulsar-client\lib\b_version=8 --inding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Devlopment\tagger\admin-service\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Devlopment\\tagger\\admin-service\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"   
npm ERR! node-pre-gyp ERR! cwd D:\Devlopment\tagger\admin-service\node_modules\pulsar-client
npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok
}

**Comment by shibd** [comment]
Hi, @AhmedAymanBfcai, `pulsar-client@1.8.0-rc.2` was a temporary version and now its binaries have been deleted.

```
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-node/pulsar-client-node-1.8.0-candidate-2/napi-win32-unknown-x64.tar.gz
```


We have released the official version: [v1.8.0](https://github.com/apache/pulsar-client-node/releases/tag/v1.8.0)

You can use this cmd to install: `npm install pulsar-client@1.8.0`

**Comment by AhmedAymanBfcai** [comment]
Hi @shibd, Thanks again.

It works well. 

Should I expect any new version soon?
